version: 4.0.2.0-extended.{build}

branches:
    only:
        - extended

skip_tags: true

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "4.0.2.{build}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

image: Visual Studio 2017

before_build:
    - ps: (Get-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8).replace("<BUILD_VERSION>", "$env:APPVEYOR_BUILD_VERSION").replace("<BUILD_TIME>", (Get-Date -Format g)) | Set-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8
    - mkdir output-template
    - mkdir output-template\Licenses
    - copy Licenses\*.* output-template\Licenses\
    - copy LICENSE output-template\LICENSE
    - mkdir output-template\Plugins

build_script:
    - xcopy /E output-template output\
    - git submodule update --init --recursive
    - nuget restore
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release
    - move output output-net45-cef-full
    - xcopy /E output-net45-cef-full output-net45-cef\
    - rmdir /S /Q output-net45-cef\x86
    - rmdir /S /Q output-net45-cef\x64
    - git checkout extended-net40
    - xcopy /E output-template output\
    - git submodule sync
    - git submodule update --init --recursive
    - nuget restore
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - move output output-net40
    - ps: if (!((git branch --contains $env:APPVEYOR_REPO_COMMIT) -like '*extended-net40')) { exit -1 }

artifacts:
    - path: output-net45-cef-full
      name: 74eoe-cef-full-$(APPVEYOR_BUILD_VERSION)
    - path: output-net45-cef
      name: 74eoe-cef-$(APPVEYOR_BUILD_VERSION)
    - path: output-net40
      name: 74eoe-net40-$(APPVEYOR_BUILD_VERSION)

deploy:
  provider: GitHub
  auth_token:
    secure: LRyrixQEgYtxLDVKSCkxkjmAzMS4gi+DABeBjkT1r9Tunat6Satr15XuwkCWwoY0
  artifact: /.*/
  on:
    branch: extended
